import { readFile, readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import {
  caseDocumentSchema,
  noteDocumentSchema,
  type CaseDocumentMetadata,
  type NoteDocumentMetadata,
} from "../src/sites/personal-homepage/content/content-schema";

const contentRoot = path.join(process.cwd(), "src", "sites", "personal-homepage", "content");
const documentRoot = path.join(contentRoot, "documents");
const outputPath = path.join(contentRoot, "generated", "content-registry.ts");
const checkOnly = process.argv.includes("--check");

async function readDocuments<T>(directory: "cases" | "notes", parse: (value: unknown) => T) {
  const directoryPath = path.join(documentRoot, directory);
  const names = (await readdir(directoryPath)).filter((name) => name.endsWith(".mdx")).sort();
  return Promise.all(names.map(async (name) => {
    const source = await readFile(path.join(directoryPath, name), "utf8");
    const document = matter(source);
    const metadata = parse(document.data);
    if (/\b[a-zA-Z][a-zA-Z0-9]*=\{"/.test(document.content)) {
      throw new Error(`${directory}/${name} uses an MDX expression for a string prop; use quoted attributes instead`);
    }
    if (!document.content.includes('<LocaleBlock locale="zh">') || !document.content.includes('<LocaleBlock locale="en">')) {
      throw new Error(`${directory}/${name} must contain both zh and en LocaleBlock sections`);
    }
    return metadata;
  }));
}

function ensureUnique(values: readonly string[], label: string) {
  if (new Set(values).size !== values.length) throw new Error(`Duplicate ${label} slug`);
}

function ensureRelations(cases: readonly CaseDocumentMetadata[], notes: readonly NoteDocumentMetadata[]) {
  const caseSlugs = new Set(cases.map((entry) => entry.slug));
  const noteSlugs = new Set(notes.map((entry) => entry.slug));
  for (const entry of cases) {
    for (const noteSlug of entry.relatedNoteSlugs) {
      if (!noteSlugs.has(noteSlug)) throw new Error(`${entry.slug} references unknown note ${noteSlug}`);
    }
  }
  for (const note of notes) {
    for (const caseSlug of note.relatedCaseSlugs) {
      if (!caseSlugs.has(caseSlug)) throw new Error(`${note.slug} references unknown case ${caseSlug}`);
    }
  }
}

function serialize(cases: readonly CaseDocumentMetadata[], notes: readonly NoteDocumentMetadata[]) {
  const caseEntries = cases.map((metadata) => {
    const { kind, schemaVersion, runtimeStatus, liveHref, ...entry } = metadata;
    void kind;
    void schemaVersion;
    return { ...entry, status: runtimeStatus, ...(liveHref ? { liveHref } : {}) };
  });
  const noteEntries = notes.map((metadata) => {
    const { kind, schemaVersion, ...entry } = metadata;
    void kind;
    void schemaVersion;
    return entry;
  });
  return `/* This file is generated by scripts/generate-cstd-content.ts. */\nimport type { CstdCaseStudy, CstdTechnicalNote } from "../content-models";\n\nexport const generatedCstdCaseStudies = ${JSON.stringify(caseEntries, null, 2)} as const satisfies readonly CstdCaseStudy[];\n\nexport const generatedCstdTechnicalNotes = ${JSON.stringify(noteEntries, null, 2)} as const satisfies readonly CstdTechnicalNote[];\n`;
}

async function main() {
  const [cases, notes] = await Promise.all([
    readDocuments("cases", (value) => caseDocumentSchema.parse(value)),
    readDocuments("notes", (value) => noteDocumentSchema.parse(value)),
  ]);
  ensureUnique(cases.map((entry) => entry.slug), "case");
  ensureUnique(notes.map((entry) => entry.slug), "note");
  ensureRelations(cases, notes);
  const output = serialize(cases, notes);

  if (checkOnly) {
    const current = await readFile(outputPath, "utf8").catch(() => "");
    if (current !== output) throw new Error("Generated CSTD content registry is stale. Run npm run content:generate.");
    return;
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) await writeFile(outputPath, output, "utf8");
}

void main();
